{
  this.futures.add(this.executor.submit(new Callable<Void>(){
    @Override public Void call() throws Exception {
      Lock lock=locks.get(src.toString());
      lock.lock();
      try {
        if (fs.exists(src)) {
          HadoopUtils.renamePath(fs,src,dst);
          if (group.isPresent()) {
            HadoopUtils.setGroup(fs,dst,group.get());
          }
        }
        return null;
      }
 catch (      FileAlreadyExistsException e) {
        LOGGER.warn(String.format("Failed to rename %s to %s: dst already exists"),e);
        return null;
      }
 finally {
        lock.unlock();
      }
    }
  }
));
}
