{
  Callable<Void> writeCall=new Callable<Void>(){
    @Override public Void call() throws Exception {
      writer.write(record);
      return null;
    }
  }
;
  try {
    this.retryer.wrap(writeCall).call();
  }
 catch (  Exception e) {
    isFailure=true;
    throw new RuntimeException(e);
  }
}
